spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jiaoli_community?serverTimezone=UTC&useUnicode=true&characterEncoding=gbk
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.155.129
    port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true