spring:
  rabbitmq:
    host: 192.168.155.129
    username: guest
    password: guest

aliyun:
  sms:
    accessKeyId: 自己的ID
    accessKeySecret: 自己的秘钥
    template_code: SMS_185810657
    sing_name: 交理论坛

server:
  port: 9999
